### ISSUE TITLE
The atitd carp blade macro does not work properly

### ISSUE THREAD

**Issue by Jimbly** [DashingStrike/Automato#11]
Submitter: Jaclyn Masterson
Email: jaclyn.atitd@gmail.com
When you are trying to make a carp blade your avatar runs off because it clicks places besides the anvil, even if you pin your avatar down the macro only produces an 2510 carp blade. Thank you for your amazing program :)

**Comment by Jimbly** [comment]
Moved to [Automato-ATITD](https://github.com/DashingStrike/Automato-ATITD/issues/66)

**Comment by Cegaiel** [comment]
https://github.com/DashingStrike/Automato-ATITD/issues/66
