### ISSUE TITLE
Feature Request: Start/Stop Command Customization

### ISSUE THREAD

**Issue by TheHuggz** [DashingStrike/Automato#14]
During my day to day I frequently use the Ctrl + Shift and Alt + Shift keystrokes to perform a multitude of actions on my computer.  Automato using these as the cancel/pause commands makes it impossible for me to do anything else while macroing.  It would be nice if these key strokes could either be configured via settings.txt OR to be able to set a flag requiring the inputs to come from the alt/shift/ctrl keys on the right side of the keyboard and ignoring the left.

**Comment by Jimbly** [comment]
Hi TheHuggz,

A Tale in the Desert rules stipulate that unattended macroing is not allowed, so if you're running a macro in the background while doing other things on the computer... ;)

I'll assume you're using Automato for some other purpose though, and, yeah, I can't remember how many times I've ran into this myself, but the actual checking of which keys do what is by convention (in the game-specific scripts) and not part of Automato itself, so I've avoided changing anything.  However, your idea of just using the right keys is a nice solution (scripts are still checking for "shift" being held, Automato just reinterprets that as "right shift")!

As of version 2.13, released moments ago, settings.txt includes options to remap the "shift", "alt" and "control" keys to any keycodes you want.  An example of remapping to the right side of the keyboard only is on the newly created [settings documentation page](https://github.com/DashingStrike/Automato/wiki/Settings).
