### ISSUE TITLE
Repository request for Chariot_Stop.lua

### ISSUE THREAD

**Issue by ghost** [DashingStrike/Automato#2]
Hi, I've read the message below at http://www.dashingstrike.com/Automato/ 

"If you have a script collection (or even a single script!) for a game not currently in Automato's list, please contact us and we will happily create an "official" repository for them with you as a maintainer."

I've been working on a chariot stop macro for ATITD players. It is my first VT/Automato script so im not a contributor for the repository yet. Hopefuly this is the right place to post this. 

Files can be found here: https://github.com/safa/ATITD

**Comment by Jimbly** [comment]
For adding scripts to the ATITD, the easiest way is to fork [the Automato-ATITD repo](https://github.com/DashingStrike/Automato-ATITD), make changes to your fork and submit a pull request.  There are some quick instructions [here](https://github.com/DashingStrike/Automato/wiki/Getting-Started-with-Automato-and-Git#automato-specific), I'll be happy to help if there's any confusion.

If you've never submitted a pull request on GitHub before, it's quite straightforward - once you've pushed anything to your fork, there will be a button in the GitHub UI for submitting a pull request.

**Comment by ghost** [comment]
Sorry, im still quite new to Github. Pull request sent. Please let me know if messed up :)
